
baseURL = "https://rescueblast.com/"
languageCode = "en-us"
title = "RescueBlast"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
